/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'glossary',
    'notation',
    {
      type: 'category',
      label: 'Module 1: ROS 2',
      items: ['module-01-ros2/01-introduction', 'module-01-ros2/02-setup', 'module-01-ros2/03-communication', 'module-01-ros2/04-urdf'],
    },
  ],
   */
};

export default sidebars;
